#include <TFT_eSPI.h>
#include <SPI.h>

#define COLOR_BLUE TFT_RED
#define COLOR_RED TFT_BLUE
#define COLOR_WHITE TFT_WHITE
#define COLOR_BLACK TFT_BLACK
#define COLOR_LIGHTGREEN TFT_GREEN
#define COLOR_GREEN TFT_DARKGREEN
#define COLOR_YELLOW TFT_CYAN
#define COLOR_OLIVE TFT_DARKCYAN
#define COLOR_DARKBLUE TFT_OLIVE
#define COLOR_DARKGRAY TFT_DARKGREY
#define COLOR_LIGHTGRAY TFT_LIGHTGREY
#define COLOR_SILVER TFT_SILVER
#define COLOR_SANDY TFT_SKYBLUE

#define FOREGROUND_COLOR COLOR_WHITE
#define BACKGROUND_COLOR COLOR_BLACK

bool setupDisplay();
void displayRGB565(unsigned char*, int, int);